services:
  frontend:
    image: detect_frontend
    ports:
      - "8050:80"
    environment:
      - REACT_APP_API_HOST=${HOST:-localhost}
      - REACT_APP_API_PORT=8051
      - REACT_APP_API_NOT_SECURE=true
    depends_on:
      - backend

  backend:
    image: detect_api
    ports:
      - "8051:8000"
    environment:
      - FRONTEND_HOST=${HOST:-localhost}
      - FRONTEND_PORT=8050
    volumes:
      - ./detect-object-api:/app
