services:
  frontend:
    image: terra1313/detector:frontend-v1
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_HOST=backend
      - REACT_APP_API_PORT=8000
      - REACT_APP_API_NOT_SECURE=true
    depends_on:
      - backend

  backend:
    image: terra1313/detector:backend-v1
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_HOST=${DOMAIN_NAME:-frontend}
      - FRONTEND_PORT=3000
    volumes:
      - ./detect-object-api:/app