apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: detect-object
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: terra1313/detector:frontend-v1
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_HOST
              value: "api-service"
            - name: REACT_APP_API_PORT
              value: "8000"

